language: node_js
node_js:
  - 12.18.3

cache:
  directories:
    - ./node_modules

install:
  - npm install
  - npm install -g @angular/cli

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
